name: RITE Integration Workflow

# Runs whenever a pull request is created, reopened, or modified

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

# Runs integration workflow as a CI check:
# - Builds RITE source and runs unit tests

jobs:
  integration:
    container:
      image: maven:${{ matrix.maven-version }}
      volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        maven-version: [ 3.9.5 ]
        os: [ ubuntu-22.04 ]

    steps:
    - name: Check out RITE source
      uses: actions/checkout@v4.2.2

    - name: Set up Java and Maven
      uses: actions/setup-java@v4.7.1
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Build RITE source
      run: mvn -B package -f tools/rite/pom.xml -Dtycho.localArtifacts=ignore
