# Runs whenever the main branch is changed (except for tags)

name: RITE Main Workflow

on:
  push:
    branches: [ main, march-release-v3 ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

# Builds RITE source with Java and Maven
# Caches Maven dependencies

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        os: [ ubuntu-22.04 ]

    steps:
    - name: Check out RITE source
      uses: actions/checkout@v3.5.0

    - name: Set up Java and Maven
      uses: actions/setup-java@v3.11.0
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Build RITE source
      run: mvn -B package -f tools/rack/pom.xml -Dtycho.localArtifacts=ignore
