name: RITE Main Workflow

# Runs whenever the main branch is changed (except for tags)

on:
  push:
    branches: [ main, march-release-v3 ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

# Runs main workflow and uploads build artifacts:
# - Builds RITE source and runs unit tests

jobs:
  main:
    container:
      image: maven:${{ matrix.maven-version }}
      volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        maven-version: [ 3.9.5 ]
        os: [ ubuntu-22.04 ]

    steps:
    - name: Check out RITE source
      uses: actions/checkout@v4.1.1

    - name: Set up Java and Maven
      uses: actions/setup-java@v4.0.0
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Build RITE source
      run: mvn -B package -f tools/rack/pom.xml -Dtycho.localArtifacts=ignore
