name: RITE Release Workflow

# Runs whenever a release is published on GitHub

on:
  release:
    types: [ published ]

# Runs release workflow and uploads build artifacts:
# - Builds RITE source and runs unit tests
# - Uploads RITE zips to release page

jobs:
  release:
    container:
      image: maven:${{ matrix.maven-version }}
      volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 17 ]
        maven-version: [ 3.9.5 ]
        os: [ ubuntu-22.04 ]

    steps:
    - name: Check out RITE source
      uses: actions/checkout@v4.1.5

    - name: Set up Java and Maven
      uses: actions/setup-java@v4.2.1
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Build RITE source
      run: mvn -B package -f tools/rack/pom.xml -Dtycho.localArtifacts=ignore

    - name: Rename RITE zips
      run: |
        cd tools/rack/rack.product/target/products
        mv *-linux.gtk.x86_64.zip RITE-linux.gtk.x86_64-${{ github.event.release.tag_name }}.zip
        mv *-macosx.cocoa.x86_64.zip RITE-macosx.cocoa.x86_64-${{ github.event.release.tag_name }}.zip
        mv *-win32.win32.x86_64.zip RITE-win32.win32.x86_64-${{ github.event.release.tag_name }}.zip

    - name: Upload RITE zips to release page
      uses: softprops/action-gh-release@v2.0.4
      with:
        files: tools/rack/rack.product/target/products/*.zip
